/// Flutter icons ZonbleNumbers
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  ZonbleNumbers
///      fonts:
///       - asset: fonts/ZonbleNumbers.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class ZonbleNumbers {
  ZonbleNumbers._();

  static const _kFontFam = 'ZonbleNumbers';

  static const IconData zero = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData one = const IconData(0xe801, fontFamily: _kFontFam);
  static const IconData two = const IconData(0xe803, fontFamily: _kFontFam);
  static const IconData three = const IconData(0xe804, fontFamily: _kFontFam);
  static const IconData four = const IconData(0xe805, fontFamily: _kFontFam);
  static const IconData five = const IconData(0xe806, fontFamily: _kFontFam);
  static const IconData six = const IconData(0xe807, fontFamily: _kFontFam);
  static const IconData seven = const IconData(0xe808, fontFamily: _kFontFam);
  static const IconData eight = const IconData(0xe809, fontFamily: _kFontFam);
  static const IconData nine = const IconData(0xe80a, fontFamily: _kFontFam);
}
